#!/usr/bin/env python3
"""sauravtranspile — Transpile sauravcode (.srv) to readable Python.

Converts .srv source files into clean, idiomatic Python 3 code.
This enables sauravcode prototypes to be deployed as Python scripts,
integrated into Python projects, or used as a learning bridge between
the two languages.

The transpiler reuses the sauravcode parser to build an AST, then
walks it to emit Python source.  Most language features map naturally:

  - Functions → ``def`` with Python indentation
  - For loops → ``for i in range(start, end)``
  - For-each → ``for item in collection``
  - Match/case → Python 3.10+ ``match``/``case``
  - Pipe ``|>`` → nested function calls
  - Enums → ``enum.IntEnum`` subclasses
  - Try/catch → ``try``/``except``
  - F-strings, lambdas, list comprehensions → direct equivalents

Builtins that have direct Python equivalents (len, print, range, etc.)
are emitted as-is.  Sauravcode-specific builtins (contains, starts_with,
etc.) are emitted as method calls or helper function calls with a small
runtime preamble.

Usage::

    python sauravtranspile.py program.srv                  # print to stdout
    python sauravtranspile.py program.srv -o program.py    # write to file
    python sauravtranspile.py program.srv --no-preamble    # skip runtime helpers
    python sauravtranspile.py program.srv --verify         # transpile + run both, compare output

CLI::

    python sauravtranspile.py input.srv [-o OUTPUT] [--no-preamble] [--verify]
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys

# Import parser and AST nodes from the interpreter
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from saurav import (
    tokenize, Parser,
    AssignmentNode, FunctionNode, ReturnNode, YieldNode,
    BinaryOpNode, NumberNode, StringNode, IdentifierNode,
    PrintNode, FunctionCallNode, CompareNode, LogicalNode,
    UnaryOpNode, BoolNode, IfNode, WhileNode, ForNode,
    ListNode, IndexNode, AppendNode, PopNode, LenNode,
    MapNode, FStringNode, IndexedAssignmentNode, ForEachNode,
    TryCatchNode, ThrowNode, LambdaNode, PipeNode, ImportNode,
    ListComprehensionNode, MatchNode, CaseNode, EnumNode,
    EnumAccessNode, SliceNode, AssertNode, BreakNode,
    ContinueNode, TernaryNode,
)


# ── Runtime preamble ────────────────────────────────────────────────

RUNTIME_PREAMBLE = '''\
"""Auto-generated by sauravtranspile. Runtime helpers for sauravcode builtins."""

import math as _math
import random as _random
import json as _json
import re as _re
import time as _time
import hashlib as _hashlib
import base64 as _base64
from enum import IntEnum as _IntEnum
from datetime import datetime as _datetime


def _srv_contains(s, sub):
    return sub in s

def _srv_starts_with(s, prefix):
    return s.startswith(prefix)

def _srv_ends_with(s, suffix):
    return s.endswith(suffix)

def _srv_index_of(s, sub):
    return s.find(sub)

def _srv_char_at(s, i):
    return s[int(i)]

def _srv_substring(s, start, end=None):
    return s[int(start):int(end)] if end is not None else s[int(start):]

def _srv_trim(s):
    return s.strip()

def _srv_replace(s, old, new):
    return s.replace(old, new)

def _srv_split(s, sep=None):
    return s.split(sep)

def _srv_join(sep, lst):
    return sep.join(str(x) for x in lst)

def _srv_pad_left(s, width, ch=" "):
    return str(s).rjust(int(width), ch)

def _srv_pad_right(s, width, ch=" "):
    return str(s).ljust(int(width), ch)

def _srv_repeat(s, n):
    return s * int(n)

def _srv_char_code(s):
    return ord(s[0]) if s else 0

def _srv_from_char_code(n):
    return chr(int(n))

def _srv_upper(s):
    return s.upper()

def _srv_lower(s):
    return s.lower()

def _srv_type_of(v):
    if isinstance(v, bool): return "bool"
    if isinstance(v, int): return "number"
    if isinstance(v, float): return "number"
    if isinstance(v, str): return "string"
    if isinstance(v, list): return "list"
    if isinstance(v, dict): return "map"
    return type(v).__name__

def _srv_to_string(v):
    if isinstance(v, bool): return "true" if v else "false"
    if isinstance(v, float) and v == int(v): return str(int(v))
    return str(v)

def _srv_to_number(v):
    try: return int(v)
    except ValueError: return float(v)

def _srv_flatten(lst):
    result = []
    for item in lst:
        if isinstance(item, list): result.extend(item)
        else: result.append(item)
    return result

def _srv_unique(lst):
    seen = set()
    result = []
    for item in lst:
        key = str(item)
        if key not in seen:
            seen.add(key)
            result.append(item)
    return result

def _srv_chunk(lst, size):
    size = int(size)
    return [lst[i:i+size] for i in range(0, len(lst), size)]

def _srv_find(lst, fn):
    for item in lst:
        if fn(item): return item
    return None

def _srv_find_index(lst, fn):
    for i, item in enumerate(lst):
        if fn(item): return i
    return -1

def _srv_clamp(val, lo, hi):
    return max(lo, min(hi, val))

def _srv_lerp(a, b, t):
    return a + (b - a) * t

def _srv_remap(val, in_lo, in_hi, out_lo, out_hi):
    t = (val - in_lo) / (in_hi - in_lo)
    return out_lo + t * (out_hi - out_lo)

def _srv_mean(lst):
    return sum(lst) / len(lst) if lst else 0

def _srv_median(lst):
    s = sorted(lst)
    n = len(s)
    if n == 0: return 0
    mid = n // 2
    return (s[mid-1] + s[mid]) / 2 if n % 2 == 0 else s[mid]

def _srv_stdev(lst):
    if len(lst) < 2: return 0.0
    m = _srv_mean(lst)
    return _math.sqrt(sum((x-m)**2 for x in lst) / (len(lst)-1))

def _srv_variance(lst):
    if len(lst) < 2: return 0.0
    m = _srv_mean(lst)
    return sum((x-m)**2 for x in lst) / (len(lst)-1)

def _srv_mode(lst):
    from collections import Counter
    c = Counter(lst)
    return c.most_common(1)[0][0] if c else None

def _srv_percentile(lst, p):
    s = sorted(lst)
    k = (len(s) - 1) * p / 100
    f = int(k)
    c = f + 1
    if c >= len(s): return s[f]
    return s[f] + (k - f) * (s[c] - s[f])

def _srv_print(value):
    if isinstance(value, bool):
        print("true" if value else "false")
    elif isinstance(value, float) and value == int(value):
        print(int(value))
    elif isinstance(value, list):
        print("[" + ", ".join(_srv_to_string(x) for x in value) + "]")
    elif isinstance(value, dict):
        pairs = ", ".join(f"{k}: {_srv_to_string(v)}" for k, v in value.items())
        print("{" + pairs + "}")
    else:
        print(value)

'''


# ── Builtin mapping ────────────────────────────────────────────────

# Maps sauravcode builtin name → Python expression template.
# {0}, {1}, ... are positional arguments.
_BUILTIN_MAP = {
    # String methods → method calls
    'upper':       '{0}.upper()',
    'lower':       '{0}.lower()',
    'trim':        '_srv_trim({0})',
    'replace':     '_srv_replace({0}, {1}, {2})',
    'split':       '_srv_split({0}, {1})',
    'join':        '_srv_join({0}, {1})',
    'contains':    '_srv_contains({0}, {1})',
    'starts_with': '_srv_starts_with({0}, {1})',
    'ends_with':   '_srv_ends_with({0}, {1})',
    'substring':   '_srv_substring({0}, {1}, {2})',
    'index_of':    '_srv_index_of({0}, {1})',
    'char_at':     '_srv_char_at({0}, {1})',
    'pad_left':    '_srv_pad_left({0}, {1})',
    'pad_right':   '_srv_pad_right({0}, {1})',
    'repeat':      '_srv_repeat({0}, {1})',
    'char_code':   '_srv_char_code({0})',
    'from_char_code': '_srv_from_char_code({0})',
    # Math
    'abs':         'abs({0})',
    'round':       'round({0})',
    'floor':       '_math.floor({0})',
    'ceil':        '_math.ceil({0})',
    'sqrt':        '_math.sqrt({0})',
    'power':       '{0} ** {1}',
    'sin':         '_math.sin({0})',
    'cos':         '_math.cos({0})',
    'tan':         '_math.tan({0})',
    'log':         '_math.log({0})',
    'log10':       '_math.log10({0})',
    'min':         'min({0}, {1})',
    'max':         'max({0}, {1})',
    'pi':          '_math.pi',
    'euler':       '_math.e',
    # Type
    'type_of':     '_srv_type_of({0})',
    'to_string':   '_srv_to_string({0})',
    'to_number':   '_srv_to_number({0})',
    'input':       'input({0})',
    # Collections
    'range':       'list(range({0}))',
    'reverse':     'list(reversed({0}))',
    'sort':        'sorted({0})',
    'len':         'len({0})',
    'keys':        'list({0}.keys())',
    'values':      'list({0}.values())',
    'has_key':     '{1} in {0}',
    'zip':         'list(zip({0}, {1}))',
    'enumerate':   'list(enumerate({0}))',
    'flatten':     '_srv_flatten({0})',
    'unique':      '_srv_unique({0})',
    'count':       '{0}.count({1})',
    'sum':         'sum({0})',
    'any':         'any({0})',
    'all':         'all({0})',
    'slice':       '{0}[int({1}):int({2})]',
    'chunk':       '_srv_chunk({0}, {1})',
    'find':        '_srv_find({0}, {1})',
    'find_index':  '_srv_find_index({0}, {1})',
    # Random
    'random':      '_random.random()',
    'random_int':  '_random.randint(int({0}), int({1}))',
    'random_choice': '_random.choice({0})',
    'random_shuffle': '_random.sample({0}, len({0}))',
    # Stats
    'mean':        '_srv_mean({0})',
    'median':      '_srv_median({0})',
    'stdev':       '_srv_stdev({0})',
    'variance':    '_srv_variance({0})',
    'mode':        '_srv_mode({0})',
    'percentile':  '_srv_percentile({0}, {1})',
    'clamp':       '_srv_clamp({0}, {1}, {2})',
    'lerp':        '_srv_lerp({0}, {1}, {2})',
    'remap':       '_srv_remap({0}, {1}, {2}, {3}, {4})',
    # File I/O
    'read_file':   'open({0}).read()',
    'write_file':  'open({0}, "w").write({1})',
    'append_file': 'open({0}, "a").write({1})',
    'file_exists': '_os.path.isfile({0})',
    'read_lines':  'open({0}).read().splitlines()',
    # JSON
    'json_parse':     '_json.loads({0})',
    'json_stringify': '_json.dumps({0})',
    'json_pretty':    '_json.dumps({0}, indent=2)',
    # Regex
    'regex_match':     'bool(_re.match({1}, {0}))',
    'regex_find':      '(_re.search({1}, {0}).group() if _re.search({1}, {0}) else "")',
    'regex_find_all':  '_re.findall({1}, {0})',
    'regex_replace':   '_re.sub({1}, {2}, {0})',
    'regex_split':     '_re.split({1}, {0})',
    # Date/time
    'now':             '_datetime.now().isoformat()',
    'timestamp':       'int(_time.time())',
    'sleep':           '_time.sleep({0})',
    # Hash/encoding
    'md5':             '_hashlib.md5({0}.encode()).hexdigest()',
    'sha256':          '_hashlib.sha256({0}.encode()).hexdigest()',
    'sha1':            '_hashlib.sha1({0}.encode()).hexdigest()',
    'base64_encode':   '_base64.b64encode({0}.encode()).decode()',
    'base64_decode':   '_base64.b64decode({0}).decode()',
    'hex_encode':      '{0}.encode().hex()',
    'hex_decode':      'bytes.fromhex({0}).decode()',
}

# Builtins that are zero-arg (called without parens in sauravcode)
_ZERO_ARG_BUILTINS = {'now', 'timestamp', 'pi', 'euler', 'random'}

# Python reserved words that need renaming
_PYTHON_RESERVED = frozenset({
    'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue',
    'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from',
    'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not',
    'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield',
    'True', 'False', 'None', 'print', 'type', 'list', 'map', 'filter',
    'range', 'input', 'len', 'sum', 'any', 'all', 'min', 'max', 'sorted',
    'reversed', 'enumerate', 'zip', 'round', 'abs', 'int', 'float', 'str',
    'bool', 'dict', 'set', 'tuple',
})


# ── Transpiler ──────────────────────────────────────────────────────

class PythonTranspiler:
    """Walk a sauravcode AST and emit Python source code."""

    def __init__(self, *, include_preamble: bool = True):
        self.include_preamble = include_preamble
        self._indent = 0
        self._lines: list[str] = []
        self._enums: dict[str, list[str]] = {}  # name → variant list
        self._used_runtime = False  # track if runtime helpers are needed

    def transpile(self, source: str) -> str:
        """Parse sauravcode source and return Python source."""
        tokens = list(tokenize(source))
        parser = Parser(tokens)
        ast_nodes = parser.parse()

        self._indent = 0
        self._lines = []
        self._enums = {}
        self._used_runtime = False

        for node in ast_nodes:
            self._emit_statement(node)

        body = "\n".join(self._lines)

        if self.include_preamble and self._used_runtime:
            return RUNTIME_PREAMBLE + "\n" + body + "\n"
        elif self.include_preamble:
            # Minimal imports for basic programs
            preamble_lines = []
            if "import os" not in body:
                pass  # No need
            return "\n".join(preamble_lines + [body]) + "\n" if preamble_lines else body + "\n"
        else:
            return body + "\n"

    def _line(self, text: str):
        """Emit an indented line."""
        self._lines.append("    " * self._indent + text)

    def _blank(self):
        """Emit a blank line."""
        self._lines.append("")

    def _safe_name(self, name: str) -> str:
        """Rename identifiers that clash with Python builtins/keywords."""
        if name in ('print', 'type', 'list', 'map', 'filter', 'range',
                     'input', 'len', 'sum', 'any', 'all', 'min', 'max',
                     'sorted', 'reversed', 'enumerate', 'zip', 'round',
                     'abs', 'int', 'float', 'str', 'bool', 'dict', 'set'):
            return f"_{name}"
        return name

    # ── Statement emitters ──────────────────────────────────

    def _emit_statement(self, node):
        """Emit a single statement."""
        if node is None:
            return

        method = self._stmt_dispatch.get(type(node))
        if method:
            method(self, node)
        else:
            # Expression statement
            expr = self._expr(node)
            if expr:
                self._line(expr)

    def _emit_assignment(self, node):
        name = self._safe_name(node.name)
        value = self._expr(node.expression)
        self._line(f"{name} = {value}")

    def _emit_function(self, node):
        name = self._safe_name(node.name)
        params = ", ".join(self._safe_name(p) for p in node.params)
        self._blank()
        self._line(f"def {name}({params}):")
        self._indent += 1
        if not node.body:
            self._line("pass")
        else:
            for stmt in node.body:
                self._emit_statement(stmt)
        self._indent -= 1
        self._blank()

    def _emit_return(self, node):
        value = self._expr(node.expression)
        self._line(f"return {value}")

    def _emit_yield(self, node):
        value = self._expr(node.expression)
        self._line(f"yield {value}")

    def _emit_print(self, node):
        self._used_runtime = True
        value = self._expr(node.expression)
        self._line(f"_srv_print({value})")

    def _emit_if(self, node):
        cond = self._expr(node.condition)
        self._line(f"if {cond}:")
        self._indent += 1
        if not node.body:
            self._line("pass")
        else:
            for stmt in node.body:
                self._emit_statement(stmt)
        self._indent -= 1

        for elif_cond, elif_body in (node.elif_chains or []):
            econd = self._expr(elif_cond)
            self._line(f"elif {econd}:")
            self._indent += 1
            if not elif_body:
                self._line("pass")
            else:
                for stmt in elif_body:
                    self._emit_statement(stmt)
            self._indent -= 1

        if node.else_body:
            self._line("else:")
            self._indent += 1
            for stmt in node.else_body:
                self._emit_statement(stmt)
            self._indent -= 1

    def _emit_while(self, node):
        cond = self._expr(node.condition)
        self._line(f"while {cond}:")
        self._indent += 1
        if not node.body:
            self._line("pass")
        else:
            for stmt in node.body:
                self._emit_statement(stmt)
        self._indent -= 1

    def _emit_for(self, node):
        var = self._safe_name(node.var)
        start = self._expr(node.start)
        end = self._expr(node.end)
        self._line(f"for {var} in range({start}, {end}):")
        self._indent += 1
        if not node.body:
            self._line("pass")
        else:
            for stmt in node.body:
                self._emit_statement(stmt)
        self._indent -= 1

    def _emit_for_each(self, node):
        var = self._safe_name(node.var)
        iterable = self._expr(node.iterable)
        self._line(f"for {var} in {iterable}:")
        self._indent += 1
        if not node.body:
            self._line("pass")
        else:
            for stmt in node.body:
                self._emit_statement(stmt)
        self._indent -= 1

    def _emit_try_catch(self, node):
        self._line("try:")
        self._indent += 1
        for stmt in node.body:
            self._emit_statement(stmt)
        self._indent -= 1
        error_var = self._safe_name(node.error_var)
        self._line(f"except Exception as _exc:")
        self._indent += 1
        self._line(f"{error_var} = str(_exc)")
        for stmt in node.handler:
            self._emit_statement(stmt)
        self._indent -= 1

    def _emit_throw(self, node):
        msg = self._expr(node.expression)
        self._line(f"raise RuntimeError({msg})")

    def _emit_append(self, node):
        name = self._safe_name(node.list_name)
        value = self._expr(node.value)
        self._line(f"{name}.append({value})")

    def _emit_pop(self, node):
        name = self._safe_name(node.list_name)
        self._line(f"{name}.pop()")

    def _emit_indexed_assignment(self, node):
        name = self._safe_name(node.name)
        index = self._expr(node.index)
        value = self._expr(node.value)
        self._line(f"{name}[{index}] = {value}")

    def _emit_import(self, node):
        # sauravcode imports → comment + note (Python import semantics differ)
        path = node.module_path
        if path.endswith('.srv'):
            path = path[:-4]
        self._line(f"# import \"{node.module_path}\"  (sauravcode module)")
        self._line(f"# TODO: convert {node.module_path} to Python and use: from {path.replace('/', '.')} import *")

    def _emit_match(self, node):
        expr = self._expr(node.expression)
        self._line(f"match {expr}:")
        self._indent += 1
        for case in node.cases:
            self._emit_case(case)
        self._indent -= 1

    def _emit_case(self, case):
        if case.is_wildcard:
            pattern = "_"
            if case.binding_name:
                pattern = self._safe_name(case.binding_name)
        else:
            patterns = []
            for p in case.patterns:
                patterns.append(self._expr(p))
            pattern = " | ".join(patterns)

        if case.guard:
            guard = self._expr(case.guard)
            self._line(f"case {pattern} if {guard}:")
        else:
            self._line(f"case {pattern}:")

        self._indent += 1
        if not case.body:
            self._line("pass")
        else:
            for stmt in case.body:
                self._emit_statement(stmt)
        self._indent -= 1

    def _emit_enum(self, node):
        self._used_runtime = True
        name = self._safe_name(node.name)
        self._enums[node.name] = node.variants
        self._blank()
        self._line(f"class {name}(_IntEnum):")
        self._indent += 1
        for i, variant in enumerate(node.variants):
            self._line(f"{variant} = {i}")
        self._indent -= 1
        self._blank()

    def _emit_break(self, _node):
        self._line("break")

    def _emit_continue(self, _node):
        self._line("continue")

    def _emit_assert(self, node):
        cond = self._expr(node.condition)
        if node.message:
            msg = self._expr(node.message)
            self._line(f"assert {cond}, {msg}")
        else:
            self._line(f"assert {cond}")

    def _emit_function_call_stmt(self, node):
        """Emit a function call as a statement (discard return value)."""
        expr = self._expr(node)
        self._line(expr)

    # Statement dispatch table
    _stmt_dispatch = {
        AssignmentNode:        _emit_assignment,
        FunctionNode:          _emit_function,
        ReturnNode:            _emit_return,
        YieldNode:             _emit_yield,
        PrintNode:             _emit_print,
        IfNode:                _emit_if,
        WhileNode:             _emit_while,
        ForNode:               _emit_for,
        ForEachNode:           _emit_for_each,
        TryCatchNode:          _emit_try_catch,
        ThrowNode:             _emit_throw,
        AppendNode:            _emit_append,
        PopNode:               _emit_pop,
        IndexedAssignmentNode: _emit_indexed_assignment,
        ImportNode:            _emit_import,
        MatchNode:             _emit_match,
        EnumNode:              _emit_enum,
        BreakNode:             _emit_break,
        ContinueNode:          _emit_continue,
        AssertNode:            _emit_assert,
        FunctionCallNode:      _emit_function_call_stmt,
    }

    # ── Expression emitters ─────────────────────────────────

    def _expr(self, node) -> str:
        """Convert an AST expression node to a Python expression string."""
        if node is None:
            return "None"

        method = self._expr_dispatch.get(type(node))
        if method:
            return method(self, node)

        return repr(node)  # Fallback

    def _expr_number(self, node):
        v = node.value
        if isinstance(v, float) and v == int(v):
            return str(int(v))
        return str(v)

    def _expr_string(self, node):
        return repr(node.value)

    def _expr_bool(self, node):
        return "True" if node.value else "False"

    def _expr_identifier(self, node):
        return self._safe_name(node.name)

    def _expr_binary_op(self, node):
        left = self._expr(node.left)
        right = self._expr(node.right)
        op = node.operator
        return f"({left} {op} {right})"

    def _expr_compare(self, node):
        left = self._expr(node.left)
        right = self._expr(node.right)
        return f"({left} {node.operator} {right})"

    def _expr_logical(self, node):
        left = self._expr(node.left)
        right = self._expr(node.right)
        op = node.operator  # 'and' / 'or' — same in Python
        return f"({left} {op} {right})"

    def _expr_unary(self, node):
        operand = self._expr(node.operand)
        if node.operator == 'not':
            return f"(not {operand})"
        return f"(-{operand})"

    def _expr_list(self, node):
        elems = ", ".join(self._expr(e) for e in node.elements)
        return f"[{elems}]"

    def _expr_index(self, node):
        obj = self._expr(node.obj)
        index = self._expr(node.index)
        return f"{obj}[{index}]"

    def _expr_slice(self, node):
        obj = self._expr(node.obj)
        start = self._expr(node.start) if node.start else ""
        end = self._expr(node.end) if node.end else ""
        return f"{obj}[{start}:{end}]"

    def _expr_len(self, node):
        inner = self._expr(node.expression)
        return f"len({inner})"

    def _expr_pop(self, node):
        name = self._safe_name(node.list_name)
        return f"{name}.pop()"

    def _expr_map(self, node):
        pairs = ", ".join(
            f"{self._expr(k)}: {self._expr(v)}" for k, v in node.pairs
        )
        return f"{{{pairs}}}"

    def _expr_fstring(self, node):
        parts = []
        for part in node.parts:
            if isinstance(part, StringNode):
                # Literal text in f-string — escape braces
                text = part.value.replace("{", "{{").replace("}", "}}")
                parts.append(text)
            else:
                expr = self._expr(part)
                parts.append("{" + expr + "}")
        return 'f"' + "".join(parts) + '"'

    def _expr_lambda(self, node):
        params = ", ".join(self._safe_name(p) for p in node.params)
        body = self._expr(node.body_expr)
        return f"(lambda {params}: {body})"

    def _expr_pipe(self, node):
        """Pipe: a |> f → f(a)"""
        value = self._expr(node.value)
        func = self._expr(node.function)
        return f"{func}({value})"

    def _expr_enum_access(self, node):
        name = self._safe_name(node.enum_name)
        return f"{name}.{node.variant_name}"

    def _expr_ternary(self, node):
        true_expr = self._expr(node.true_expr)
        cond = self._expr(node.condition)
        false_expr = self._expr(node.false_expr)
        return f"({true_expr} if {cond} else {false_expr})"

    def _expr_list_comprehension(self, node):
        expr = self._expr(node.expr)
        var = self._safe_name(node.var)
        iterable = self._expr(node.iterable)
        if node.condition:
            cond = self._expr(node.condition)
            return f"[{expr} for {var} in {iterable} if {cond}]"
        return f"[{expr} for {var} in {iterable}]"

    def _expr_function_call(self, node):
        """Emit a function call expression."""
        name = node.name
        args = [self._expr(a) for a in node.arguments]

        # Zero-arg builtins
        if name in _ZERO_ARG_BUILTINS and len(args) == 0:
            template = _BUILTIN_MAP.get(name)
            if template:
                self._used_runtime = True
                return template

        # Mapped builtins
        if name in _BUILTIN_MAP:
            template = _BUILTIN_MAP[name]
            self._used_runtime = True
            try:
                return template.format(*args)
            except (IndexError, KeyError):
                pass  # Fall through to generic call

        # Higher-order builtins (map/filter/reduce/each)
        if name == 'map' and len(args) == 2:
            return f"list(map({args[0]}, {args[1]}))"
        if name == 'filter' and len(args) == 2:
            return f"list(filter({args[0]}, {args[1]}))"
        if name == 'reduce' and len(args) >= 2:
            self._used_runtime = True
            if len(args) == 3:
                return f"__import__('functools').reduce({args[0]}, {args[1]}, {args[2]})"
            return f"__import__('functools').reduce({args[0]}, {args[1]})"
        if name == 'each' and len(args) == 2:
            return f"[{args[0]}(x) for x in {args[1]}]"

        # Collect/is_generator
        if name == 'collect' and len(args) == 1:
            return f"list({args[0]})"
        if name == 'is_generator' and len(args) == 1:
            return f"hasattr({args[0]}, '__next__')"

        # User-defined function
        safe_name = self._safe_name(name)
        arg_str = ", ".join(args)
        return f"{safe_name}({arg_str})"

    # Expression dispatch table
    _expr_dispatch = {
        NumberNode:             _expr_number,
        StringNode:             _expr_string,
        BoolNode:               _expr_bool,
        IdentifierNode:         _expr_identifier,
        BinaryOpNode:           _expr_binary_op,
        CompareNode:            _expr_compare,
        LogicalNode:            _expr_logical,
        UnaryOpNode:            _expr_unary,
        ListNode:               _expr_list,
        IndexNode:              _expr_index,
        SliceNode:              _expr_slice,
        LenNode:                _expr_len,
        PopNode:                _expr_pop,
        MapNode:                _expr_map,
        FStringNode:            _expr_fstring,
        LambdaNode:             _expr_lambda,
        PipeNode:               _expr_pipe,
        EnumAccessNode:         _expr_enum_access,
        TernaryNode:            _expr_ternary,
        ListComprehensionNode:  _expr_list_comprehension,
        FunctionCallNode:       _expr_function_call,
    }


# ── Convenience functions ───────────────────────────────────────────

def transpile(source: str, *, include_preamble: bool = True) -> str:
    """Transpile sauravcode source to Python source.

    Parameters
    ----------
    source : str
        Sauravcode source code.
    include_preamble : bool
        Whether to include the runtime preamble (default True).

    Returns
    -------
    str
        Python source code.
    """
    t = PythonTranspiler(include_preamble=include_preamble)
    return t.transpile(source)


def transpile_file(input_path: str, output_path: str | None = None,
                   *, include_preamble: bool = True) -> str:
    """Transpile a .srv file to Python.

    Parameters
    ----------
    input_path : str
        Path to the .srv source file.
    output_path : str or None
        If given, write the Python source to this file.
    include_preamble : bool
        Whether to include the runtime preamble.

    Returns
    -------
    str
        Python source code.
    """
    with open(input_path, "r", encoding="utf-8") as f:
        source = f.read()

    python_code = transpile(source, include_preamble=include_preamble)

    if output_path:
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(python_code)

    return python_code


def verify(source: str) -> dict:
    """Transpile and run both versions, compare output.

    Parameters
    ----------
    source : str
        Sauravcode source code.

    Returns
    -------
    dict
        Keys: 'match' (bool), 'srv_output', 'py_output', 'python_code'.
    """
    import tempfile

    python_code = transpile(source, include_preamble=True)

    # Run sauravcode
    with tempfile.NamedTemporaryFile(mode='w', suffix='.srv', delete=False,
                                     encoding='utf-8') as f:
        f.write(source)
        srv_path = f.name

    try:
        srv_result = subprocess.run(
            [sys.executable, os.path.join(os.path.dirname(__file__), 'saurav.py'), srv_path],
            capture_output=True, text=True, timeout=10,
        )
        srv_output = srv_result.stdout
    except subprocess.TimeoutExpired:
        srv_output = "<timeout>"
    finally:
        os.unlink(srv_path)

    # Run Python
    with tempfile.NamedTemporaryFile(mode='w', suffix='.py', delete=False,
                                     encoding='utf-8') as f:
        f.write(python_code)
        py_path = f.name

    try:
        py_result = subprocess.run(
            [sys.executable, py_path],
            capture_output=True, text=True, timeout=10,
        )
        py_output = py_result.stdout
    except subprocess.TimeoutExpired:
        py_output = "<timeout>"
    finally:
        os.unlink(py_path)

    return {
        'match': srv_output == py_output,
        'srv_output': srv_output,
        'py_output': py_output,
        'python_code': python_code,
    }


# ── CLI ─────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Transpile sauravcode (.srv) to Python",
    )
    parser.add_argument("input", help="Input .srv file")
    parser.add_argument("-o", "--output", help="Output .py file (default: stdout)")
    parser.add_argument("--no-preamble", action="store_true",
                        help="Omit the runtime preamble")
    parser.add_argument("--verify", action="store_true",
                        help="Run both versions and compare output")
    args = parser.parse_args()

    if args.verify:
        with open(args.input, "r", encoding="utf-8") as f:
            source = f.read()
        result = verify(source)
        if result['match']:
            print("PASS: Output matches!")
        else:
            print("FAIL: Output differs:")
            print(f"  sauravcode: {result['srv_output']!r}")
            print(f"  python:     {result['py_output']!r}")
        if args.output:
            with open(args.output, "w", encoding="utf-8") as f:
                f.write(result['python_code'])
            print(f"  Python saved to: {args.output}")
    else:
        python_code = transpile_file(
            args.input, args.output,
            include_preamble=not args.no_preamble,
        )
        if not args.output:
            print(python_code, end="")
        else:
            print(f"Transpiled to: {args.output}")


if __name__ == "__main__":
    main()
