#!/usr/bin/env python3
"""sauravgen -- Code generator / scaffolder for sauravcode projects.

Generates boilerplate .srv files from built-in templates:
  - function: standalone function with docstring
  - class: class with constructor, methods, and toString
  - enum: enum type with variants
  - test: test file with test functions
  - module: module with imports/exports pattern
  - project: full project directory (src/, tests/, README, gitignore)
  - script: quick CLI script with arg parsing

Usage:
    python sauravgen.py function my_func --args "x y z"
    python sauravgen.py class Animal --fields "name species age"
    python sauravgen.py enum Color --variants "Red Green Blue"
    python sauravgen.py test my_module --functions "add subtract"
    python sauravgen.py module utils --functions "helper1 helper2"
    python sauravgen.py project myapp
    python sauravgen.py script greet --args "name greeting"
    python sauravgen.py list                         # list all templates
    python sauravgen.py --output dir/ class Foo      # write to dir/
    python sauravgen.py --dry-run project myapp      # preview only
"""

import argparse
import os
import sys
import textwrap
__version__ = "1.0.0"

# ─── Template generators ──────────────────────────────────────────

def gen_function(name, args=None, description=None):
    """Generate a standalone function .srv file."""
    params = args or []
    param_str = " ".join(params)
    desc = description or f"Performs the {name} operation"
    lines = [
        f"# {name}.srv -- {desc}",
        f"# Generated by sauravgen v{__version__}",
        "",
        f"function {name} {param_str}".rstrip(),
    ]
    if params:
        lines.append(f'    # TODO: implement {name}({", ".join(params)})')
        for p in params:
            lines.append(f'    print f"{p} = {{{p}}}"')
        lines.append(f'    return {params[0]}')
    else:
        lines.append(f"    # TODO: implement {name}")
        lines.append('    return 0')
    lines += [
        "",
        f"# --- Example usage ---",
    ]
    if params:
        example_args = " ".join(str(i + 1) for i in range(len(params)))
        lines.append(f'result = {name} {example_args}')
    else:
        lines.append(f'result = {name}')
    lines.append(f'print f"Result: {{result}}"')
    lines.append("")
    return "\n".join(lines)


def gen_class(name, fields=None, methods=None):
    """Generate a class .srv file."""
    fields = fields or ["value"]
    methods = methods or []
    lines = [
        f"# {name}.srv -- {name} class",
        f"# Generated by sauravgen v{__version__}",
        "",
        f"class {name}",
    ]
    # Constructor
    lines.append(f'    function init {" ".join(fields)}')
    for f in fields:
        lines.append(f"        self.{f} = {f}")
    lines.append("")
    # toString
    field_parts = " ".join(f'{f}={{self.{f}}}' for f in fields)
    lines.append(f"    function toString")
    lines.append(f'        return f"{name}({field_parts})"')
    lines.append("")
    # Getters
    for f in fields:
        lines.append(f"    function get_{f}")
        lines.append(f"        return self.{f}")
        lines.append("")
    # Setters
    for f in fields:
        lines.append(f"    function set_{f} {f}")
        lines.append(f"        self.{f} = {f}")
        lines.append("")
    # Custom methods
    for m in methods:
        lines.append(f"    function {m}")
        lines.append(f"        # TODO: implement {m}")
        lines.append(f"        return 0")
        lines.append("")
    # Example usage
    lines.append(f"# --- Example usage ---")
    example_vals = []
    for f in fields:
        if f in ("name", "title", "label"):
            example_vals.append(f'"example"')
        elif f in ("age", "count", "size", "value", "x", "y", "z", "width", "height"):
            example_vals.append("42")
        else:
            example_vals.append(f'"{f}_value"')
    lines.append(f'obj = {name} {" ".join(example_vals)}')
    lines.append(f'print obj.toString()')
    lines.append("")
    return "\n".join(lines)


def gen_enum(name, variants=None):
    """Generate an enum .srv file."""
    variants = variants or ["A", "B", "C"]
    lines = [
        f"# {name}.srv -- {name} enumeration",
        f"# Generated by sauravgen v{__version__}",
        "",
        f"enum {name}",
    ]
    for v in variants:
        lines.append(f"    {v}")
    lines += [
        "",
        f"# --- Example usage ---",
        f"value = {name}.{variants[0]}",
        f'print f"Value: {{value}}"',
        "",
        f"# Pattern matching",
        f"match value",
    ]
    for v in variants:
        lines.append(f'    case {name}.{v}')
        lines.append(f'        print "{v} variant"')
    lines.append("")
    return "\n".join(lines)


def gen_test(name, functions=None):
    """Generate a test file."""
    functions = functions or ["example"]
    lines = [
        f"# test_{name}.srv -- Tests for {name}",
        f"# Generated by sauravgen v{__version__}",
        f'# Run: python sauravtest.py test_{name}.srv',
        "",
    ]
    for fn in functions:
        lines.append(f"# Test {fn}")
        lines.append(f"function test_{fn}_basic")
        lines.append(f'    # TODO: implement test for {fn}')
        lines.append(f'    assert true "test_{fn}_basic should pass"')
        lines.append("")
        lines.append(f"function test_{fn}_edge_case")
        lines.append(f'    # TODO: test edge cases for {fn}')
        lines.append(f'    assert true "test_{fn}_edge_case should pass"')
        lines.append("")
    lines.append(f"# --- Run all tests ---")
    for fn in functions:
        lines.append(f"test_{fn}_basic")
        lines.append(f"test_{fn}_edge_case")
    lines.append(f'print "All {name} tests passed!"')
    lines.append("")
    return "\n".join(lines)


def gen_module(name, functions=None):
    """Generate a module file (meant to be imported)."""
    functions = functions or ["helper"]
    lines = [
        f"# {name}.srv -- {name} module",
        f"# Generated by sauravgen v{__version__}",
        f"# Usage: import {name}",
        "",
    ]
    for fn in functions:
        lines.append(f"function {fn} x")
        lines.append(f"    # TODO: implement {fn}")
        lines.append(f"    return x")
        lines.append("")
    return "\n".join(lines)


def gen_script(name, args=None):
    """Generate a CLI-style script."""
    args = args or ["input"]
    lines = [
        f"# {name}.srv -- CLI script",
        f"# Generated by sauravgen v{__version__}",
        f"# Run: python saurav.py {name}.srv",
        "",
        f'print "=== {name} ==="',
        "",
    ]
    # Simulated arg handling
    for a in args:
        lines.append(f'{a} = "{a}_default"')
    lines.append("")
    lines.append(f"function {name} {' '.join(args)}")
    for a in args:
        lines.append(f'    print f"{a}: {{{a}}}"')
    lines.append(f"    # TODO: implement main logic")
    lines.append(f"    return 0")
    lines.append("")
    lines.append(f"result = {name} {' '.join(args)}")
    lines.append(f'print f"Done (exit code: {{result}})"')
    lines.append("")
    return "\n".join(lines)


def gen_project(name):
    """Generate a full project directory structure.
    
    Returns a dict of {relative_path: content}.
    """
    files = {}
    
    # Main entry point
    files[f"{name}/main.srv"] = "\n".join([
        f"# {name} -- Main entry point",
        f"# Generated by sauravgen v{__version__}",
        "",
        f'import "{name}/lib"',
        "",
        f'print "=== {name} ==="',
        f"greet \"World\"",
        "",
    ])
    
    # Library module
    files[f"{name}/lib.srv"] = "\n".join([
        f"# {name}/lib.srv -- Core library",
        f"# Generated by sauravgen v{__version__}",
        "",
        f"function greet name",
        f'    print f"Hello, {{name}}!"',
        f"    return 0",
        "",
        f"function version",
        f'    return "0.1.0"',
        "",
    ])
    
    # Test file
    files[f"{name}/tests/test_lib.srv"] = "\n".join([
        f"# Tests for {name}/lib",
        f"# Generated by sauravgen v{__version__}",
        f'# Run: python sauravtest.py {name}/tests/test_lib.srv',
        "",
        f"function test_greet",
        f'    assert true "greet should work"',
        "",
        f"function test_version",
        f'    assert true "version should return string"',
        "",
        f"test_greet",
        f"test_version",
        f'print "All tests passed!"',
        "",
    ])
    
    # README
    files[f"{name}/README.md"] = "\n".join([
        f"# {name}",
        "",
        f"A sauravcode project.",
        "",
        f"## Usage",
        "",
        f"```bash",
        f"python saurav.py {name}/main.srv",
        f"```",
        "",
        f"## Testing",
        "",
        f"```bash",
        f"python sauravtest.py {name}/tests/test_lib.srv",
        f"```",
        "",
    ])
    
    # .gitignore
    files[f"{name}/.gitignore"] = "\n".join([
        "# sauravcode project",
        "*.pyc",
        "__pycache__/",
        ".sauravsnap/",
        "",
    ])
    
    return files


# ─── Template registry ────────────────────────────────────────────

TEMPLATES = {
    "function": {
        "description": "Standalone function with docstring and example usage",
        "generator": gen_function,
        "output_pattern": "{name}.srv",
    },
    "class": {
        "description": "Class with constructor, getters/setters, toString, and examples",
        "generator": gen_class,
        "output_pattern": "{name}.srv",
    },
    "enum": {
        "description": "Enum type with variants and pattern matching example",
        "generator": gen_enum,
        "output_pattern": "{name}.srv",
    },
    "test": {
        "description": "Test file with test functions and assertions",
        "generator": gen_test,
        "output_pattern": "test_{name}.srv",
    },
    "module": {
        "description": "Importable module with exported functions",
        "generator": gen_module,
        "output_pattern": "{name}.srv",
    },
    "script": {
        "description": "CLI-style script with argument handling",
        "generator": gen_script,
        "output_pattern": "{name}.srv",
    },
    "project": {
        "description": "Full project: src/, tests/, README, gitignore",
        "generator": gen_project,
        "output_pattern": "{name}/",
    },
}


# ─── CLI ──────────────────────────────────────────────────────────

def list_templates():
    """Print available templates."""
    print(f"sauravgen v{__version__} -- Available Templates")
    print("=" * 50)
    for name, info in TEMPLATES.items():
        pattern = info["output_pattern"].format(name="<name>")
        print(f"  {name:<12} {info['description']}")
        print(f"  {'':12} → {pattern}")
        print()


def write_file(path, content, dry_run=False):
    """Write content to a file, creating directories as needed."""
    if dry_run:
        print(f"[dry-run] Would write: {path}")
        print("-" * 40)
        # Show first 20 lines
        preview = content.split("\n")[:20]
        for line in preview:
            print(f"  {line}")
        if len(content.split("\n")) > 20:
            print(f"  ... ({len(content.split(chr(10)))} lines total)")
        print()
        return True
    
    dir_path = os.path.dirname(path)
    if dir_path:
        os.makedirs(dir_path, exist_ok=True)
    
    if os.path.exists(path):
        print(f"  ⚠ File exists: {path} (use --force to overwrite)")
        return False
    
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"  ✓ Created: {path}")
    return True


def main():
    parser = argparse.ArgumentParser(
        prog="sauravgen",
        description="Code generator / scaffolder for sauravcode projects",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent("""\
            Examples:
              sauravgen function calculate --args "x y z"
              sauravgen class Person --fields "name age email"
              sauravgen enum Status --variants "Active Inactive Pending"
              sauravgen test math_utils --functions "add subtract multiply"
              sauravgen module helpers --functions "format_name validate_email"
              sauravgen project myapp
              sauravgen script deploy --args "env target"
              sauravgen list
        """),
    )
    parser.add_argument("--version", action="version", version=f"sauravgen {__version__}")
    parser.add_argument("--output", "-o", default=".", help="Output directory (default: current)")
    parser.add_argument("--dry-run", "-n", action="store_true", help="Preview without writing files")
    parser.add_argument("--force", "-f", action="store_true", help="Overwrite existing files")
    parser.add_argument("--args", nargs="*", help="Function/script arguments")
    parser.add_argument("--fields", nargs="*", help="Class fields")
    parser.add_argument("--methods", nargs="*", help="Class methods")
    parser.add_argument("--variants", nargs="*", help="Enum variants")
    parser.add_argument("--functions", nargs="*", help="Functions for test/module templates")
    parser.add_argument("--description", "-d", help="Description for the generated code")
    parser.add_argument("template", help="Template: function|class|enum|test|module|script|project|list")
    parser.add_argument("name", nargs="?", help="Name for the generated code")

    args = parser.parse_args()

    if args.template == "list":
        list_templates()
        return

    if not args.name:
        parser.error(f"template '{args.template}' requires a name argument")

    if args.template not in TEMPLATES:
        print(f"Error: Unknown template '{args.template}'", file=sys.stderr)
        print(f"Available: {', '.join(TEMPLATES.keys())}", file=sys.stderr)
        sys.exit(1)

    template_info = TEMPLATES[args.template]
    gen = template_info["generator"]

    # Build kwargs based on template type
    kwargs = {}
    if args.template == "function":
        kwargs["args"] = args.args
        kwargs["description"] = args.description
    elif args.template == "class":
        kwargs["fields"] = args.fields
        kwargs["methods"] = args.methods
    elif args.template == "enum":
        kwargs["variants"] = args.variants
    elif args.template == "test":
        kwargs["functions"] = args.functions
    elif args.template == "module":
        kwargs["functions"] = args.functions
    elif args.template == "script":
        kwargs["args"] = args.args

    result = gen(args.name, **kwargs)

    # Handle project template (returns dict of files)
    if isinstance(result, dict):
        print(f"Scaffolding project: {args.name}/")
        created = 0
        for rel_path, content in result.items():
            full_path = os.path.join(args.output, rel_path)
            if args.force and os.path.exists(full_path) and not args.dry_run:
                os.remove(full_path)
            if write_file(full_path, content, args.dry_run):
                created += 1
        if not args.dry_run:
            print(f"\n  ✨ Project '{args.name}' created with {created} files")
            print(f"  Run: python saurav.py {args.name}/main.srv")
    else:
        # Single file output
        filename = template_info["output_pattern"].format(name=args.name)
        full_path = os.path.join(args.output, filename)
        if args.force and os.path.exists(full_path) and not args.dry_run:
            os.remove(full_path)
        if args.dry_run:
            write_file(full_path, result, dry_run=True)
        else:
            if write_file(full_path, result):
                print(f"\n  ✨ Generated: {full_path}")
            else:
                if not args.force:
                    print("  Use --force to overwrite")
                sys.exit(1)


if __name__ == "__main__":
    main()
